export const cuisineList = [
  'Amala',
  'Ewedu Soup',
  'Gbegiri',
  'Iyan (Pounded Yam)',
  'Efo Riro',
  'Ofe Onugbu (Bitterleaf Soup)',
  'Oha Soup',
  'Nsala Soup (White Soup)',
  'Fufu',
  'Tuwo Shinkafa',
  'Miyan Kuka',
  'Miyan Taushe',
  'Suya',
  'Afang Soup',
  'Edikang Ikong Soup',
  'Atama Soup',
  'Ukodo',
  'Banga Soup',
  'Starch',
  'Owho Soup',
  'Igede',
  'Owo Soup',
  'Achu Soup',
  'Efik Cuisine',
  'Ijaw Cuisine',
  'Tiv Cuisine',
  'Burger',
  'Shawarma',
  'Noodles',
  'Fried Plantain',
  'Chicken',
  'Fish',
  'Ponmo',
  'Chips',
];
